version: "3.1"
services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/auth-api
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    volumes:
      - ./dist/:/usr/src/auth-api/dist/
      - ./package.json:/usr/src/auth-api/package.json
    ports:
      - "6060:6060"
      - "9222:9222"
    links:
      - mongo