version: "3.1"
services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: auth-api
    command: npm run debug
    volumes:
      - ./dist:/usr/src/auth-api/dist
      - ./package.json:/usr/src/auth-api/package.json
    ports:
      - "6060:6060"
      - "9222:9222"
    links:
      - mongo